/**
 * Created by chenmeng on 17/08/03.
 */
export default [
    // 获取日程事件列表数据
    'FETCH_CALENDAR_LIST_DATA',
    'FETCH_CALENDAR_LIST_DATA_SUCCESS',
    'FETCH_CALENDAR_LIST_DATA_FAIL',

    // 获取单条日程事件数据
    'FETCH_CALENDAR_DATA',
    'FETCH_CALENDAR_DATA_SUCCESS',
    'FETCH_CALENDAR_DATA_FAIL',

    // 创建日程事件
    'CREATE_CALENDAR_EVENT',
    'CREATE_CALENDAR_EVENT_SUCCESS',
    'CREATE_CALENDAR_EVENT_FAIL',

    // 更新日程事件
    'UPDATE_CALENDAR_EVENT',
    'UPDATE_CALENDAR_EVENT_SUCCESS',
    'UPDATE_CALENDAR_EVENT_FAIL',

    // 删除日程事件
    'DELETE_CALENDAR_EVENT',
    'DELETE_CALENDAR_EVENT_SUCCESS',
    'DELETE_CALENDAR_EVENT_FAIL'
];
