/**
 * Created by listen1013 on 17/5/1.
 */

export default [
    // 列表页
    'FETCH_VETTING_LIST',
    'FETCH_VETTING_LIST_SUCCESS',
    'FETCH_VETTING_LIST_FAIL',

    // 详情页
    'FETCH_VETTING_DATA',
    'FETCH_VETTING_DATA_SUCCESS',
    'FETCH_VETTING_DATA_FAIL',

    // 同意
    'AUDIT_VETTING_DATA',
    'AUDIT_VETTING_DATA_SUCCESS',
    'AUDIT_VETTING_DATA_FAIL',

    // 转发
    'RELAY_VETTING_DATA',
    'RELAY_VETTING_DATA_SUCCESS',
    'RELAY_VETTING_DATA_FAIL',

    // 撤回
    'REVOKE_VETTING_DATA',
    'REVOKE_VETTING_DATA_SUCCESS',
    'REVOKE_VETTING_DATA_FAIL',

    // 在指定审批节点填写可编辑字段数据
    'UPDATA_VETTING_DATA',
    'UPDATA_VETTING_DATA_SUCCESS',
    'UPDATA_VETTING_DATA_FAIL',

    // 获取指定审批的评论列表
    'COMMENT_VETTING_DATA',
    'COMMENT_VETTING_DATA_SUCCESS',
    'COMMENT_VETTING_DATA_FAIL',

    // 在指定审批发表评论
    'CREATE_COMMENT_DATA',
    'CREATE_COMMENT_DATA_SUCCESS',
    'CREATE_COMMENT_DATA_FAIL',

    // 获取指定Record有那些字段在审批
    'RECORD_FIELDS_DATA',
    'RECORD_FIELDS_DATA_SUCCESS',
    'RECORD_FIELDS_DATA_FAIL',

    // 获取创建可用的审批模板
    'CREATE_TEMP_DATA',
    'CREATE_TEMP_DATA_SUCCESS',
    'CREATE_TEMP_DATA_FAIL',

    // 获取修改可用的审批模板
    'UPDATA_TEMP_DATA',
    'UPDATA_TEMP_DATA_SUCCESS',
    'UPDATA_TEMP_DATA_FAIL',

    'RESIT_UPDATA_TEMP_DATA',
    'RESIT_UPDATA_TEMP_DATA_SUCCESS',
    'RESIT_UPDATA_TEMP_DATA_FAIL',

    'RESIT_CREATE_APPROVAL_DATA',
    'RESIT_CREATE_APPROVAL_DATA_SUCCESS',
    'RESIT_CREATE_APPROVAL_DATA_FAIL',

    'RESIT_APPROVAL_FIELDS',
    'RESIT_APPROVAL_FIELDS_SUCCESS',
    'RESIT_APPROVAL_FIELDS_FALT',

    // 创建审批
    'CREATE_APPROVAL_DATA',
    'CREATE_APPROVAL_DATA_SUCCESS',
    'CREATE_APPROVAL_DATA_FAIL',

    // 获取每个listType的count
    'FETCH_VETTING_COUNT',
    'FETCH_VETTING_COUNT_SUCCESS',
    'FETCH_VETTING_COUNT_FAIL',

    //
    'FETCH_APPROVAL_OBJNAME',
    'FETCH_APPROVAL_OBJNAME_SUCCESS',
    'FETCH_APPROVAL_OBJNAME_FAIL'
];

