// 请求关于acl中team方面的请求
export default [
    // 获根据userId获取manager
    'FETCH_USER_MANAGER_REQUEST',
    'FETCH_USER_MANAGER_REQUEST_SUCCESS',
    'FETCH_USER_MANAGER_REQUEST_FAIL',

    // 获根据userId获取全部manager
    'FETCH_USER_ALL_MANAGER_REQUEST',
    'FETCH_USER_ALL_MANAGER_REQUEST_SUCCESS',
    'FETCH_USER_ALL_MANAGER_REQUEST_FAIL'
];
