// 请求关于acl中team方面的请求
export default [
    // 获取team_member
    'FETCH_TEAM_MEMBER_REQUEST',
    'FETCH_TEAM_MEMBER_REQUEST_SUCCESS',
    'FETCH_TEAM_MEMBER_REQUEST_FAIL',

    // 新增
    'ADD_TEAM_MEMBER_REQUEST',
    'ADD_TEAM_MEMBER_REQUEST_SUCCESS',
    'ADD_TEAM_MEMBER_REQUEST_FAIL',

    // 删除
    'REMOVE_TEAM_MEMBER_REQUEST',
    'REMOVE_TEAM_MEMBER_REQUEST_SUCCESS',
    'REMOVE_TEAM_MEMBER_REQUEST_FAIL'
];
