/**
 * Created by chenmneg on 17/8/25.
 */
export default [
    // 获取海的列表数据
    'FETCH_TERRITORY_LIST',
    'FETCH_TERRITORY_LIST_SUCCESS',
    'FETCH_TERRITORY_LIST_FAIL',

    // 海 相关的 获取海的树形结构
    'FETCH_TERRITORY_NODE',
    'FETCH_TERRITORY_NODE_SUCCESS',
    'FETCH_TERRITORY_NODE_FAIL',

    // 获取某个海的 record list
    'FETCH_TERRITORY_RECORD_LIST',
    'FETCH_TERRITORY_RECORD_LIST_SUCCESS',
    'FETCH_TERRITORY_RECORD_LIST_FAIL',

    // 领取记录
    'CLAIM_TERRITORY_RECORD',
    'CLAIM_TERRITORY_RECORD_SUCCESS',
    'CLAIM_TERRITORY_RECORD_FAIL',

    // 退回公海
    'ALLOCATE_TERRITORY',
    'ALLOCATE_TERRITORY_SUCCESS',
    'ALLOCATE_TERRITORY_FAIL'
];
