export default [
    // 获取
    'FETCH_SETTING_USER_DATA',
    'FETCH_SETTING_USER_DATA_SUCCESS',
    'FETCH_SETTING_USER_DATA_FAIL',
    // 修改
    'UPDATE_SETTING_USER_DATA',
    'UPDATE_SETTING_USER_DATA_SUCCESS',
    'UPDATE_SETTING_USER_DATA_FAIL'
];

