/**
 * 搜索
 */
export default [
    'FETCH_SEARCH_NAV',
    'FETCH_SEARCH_NAV_SUCCESS',
    'FETCH_SEARCH_NAV_FAIL',

    'FETCH_SEARCH_DATA',
    'FETCH_SEARCH_DATA_SUCCESS',
    'FETCH_SEARCH_DATA_FAIL'
];
