// 获取对象的操作actions
export default [
    'FETCH_ACTIONS_REQUEST',
    'FETCH_ACTIONS_REQUEST_SUCCESS',
    'FETCH_ACTIONS_REQUEST_FAIL',

    'FETCH_CUSTOMER_ACTION_REQUEST',
    'FETCH_CUSTOMER_ACTION_REQUEST_SUCCESS',
    'FETCH_CUSTOMER_ACTION_REQUEST_FAIL'
];
