/**
 * Created by listen1013 on 17/3/24.
 */

export default [
    'FETCH_DETAILVIEW_OBJECT',
    'FETCH_DETAILVIEW_OBJECT_SUCCESS',
    'FETCH_DETAILVIEW_OBJECT_FAIL',

    'UPDATE_DETAILVIEW_OBJECT',
    'UPDATE_DETAILVIEW_OBJECT_SUCCESS',
    'UPDATE_DETAILVIEW_OBJECT_FAIL',

    // 海的领取
    'CLAIM_DETAILVIEW_TERRITORY',
    'CLAIM_DETAILVIEW_TERRITORY_SUCCESS',
    'CLAIM_DETAILVIEW_TERRITORY_FAIL',

    // 海的退回
    'ALLOCATE_DETAILVIEW_TERRITORY',
    'ALLOCATE_DETAILVIEW_TERRITORY_SUCCESS',
    'ALLOCATE_DETAILVIEW_TERRITORY_FAIL'
];
