/**
 * Created by listen1013 on 17/3/24.
 */
export default [
    // filter 筛选器数据
    'FETCH_FILTER_DATA',
    'FETCH_FILTER_DATA_SUCCESS',
    'FETCH_FILTER_DATA_FAIL',

    'CREAT_FILTER_DATA',
    'CREAT_FILTER_DATA_SUCCESS',
    'CREAT_FILTER_DATA_FAIL',

    // 修改filter
    'UPDATE_FILTER_DATA',
    'UPDATE_FILTER_DATA_SUCCESS',
    'UPDATE_FILTER_DATA_FAIL',

    // 删除fiilter
    'DELETE_FILTER_DATA',
    'DELETE_FILTER_DATA_SUCCESS',
    'DELETE_FILTER_DATA_FAIL',

    // 列表数据
    'FETCH_LIST_DATA',
    'FETCH_LIST_DATA_SUCCESS',
    'FETCH_LIST_DATA_FAIL',
    'CREATE_DATA',
    'CREATE_DATA_SUCCESS',
    'CREATE_DATA_FAIL',
    'DELETE_DATA',
    'DELETE_DATA_SUCCESS',
    'DELETE_DATA_FAIL',
    'UPDATE_DATA',
    'UPDATE_DATA_SUCCESS',
    'UPDATE_DATA_FAIL',

    // 批量删除
    'BATCH_DELETE_LIST_DATA',
    'BATCH_DELETE_LIST_DATA_SUCCESS',
    'BATCH_DELETE_LIST_DATA_FAIL',
    // 删除hash数据
    'DELETE_HASH_DATA',
    'DELETE_HASH_DATA_SUCCESS',
    'DELETE_HASH_DATA_FAIL',
    // 列表页的全选
    'SETTING_CHECKED_ALL_LIST',
    'SETTING_CHECKED_ALL_LIST_SUCCESS',
    'SETTING_CHECKED_ALL_LIST_FAIL',
    // 列表页的清除全选
    'CLEAR_CHECKED_ALL_LIST',
    'CLEAR_CHECKED_ALL_LIST_SUCCESS',
    'CLEAR_CHECKED_ALL_LIST_FAIL',
    // 切换选中非选中
    'HANDLE_CHECKED_LIST',
    'HANDLE_CHECKED_LIST_SUCCESS',
    'HANDLE_CHECKED_LIST_FAIL',

    'ADD_TO_DATA',
    'ADD_TO_DATA_SUCCESS',
    'ADD_TO_DATA_FAIL',
    'REMOVE_TO_DATA',
    'REMOVE_TO_DATA_SUCCESS',
    'REMOVE_TO_DATA_FAIL',
    'MODIFY_TO_DATA',
    'MODIFY_TO_DATA_SUCCESS',
    'MODIFY_TO_DATA_FAIL',

    // 合并数据
    'MERGE_DATA',
    'MERGE_DATA_SUCCESS',
    'MERGE_DATA_FAIL',

    // 复制数据
    'COPY_DATA',
    'COPY_DATA_SUCCESS',
    'COPY_DATA_FAIL'
];
