/**
 * 配合相关对象,找到
 */
export default [
    'FETCH_RELATED_DATA',
    'FETCH_RELATED_DATA_SUCCESS',
    'FETCH_RELATED_DATA_FAIL',

    'CREATE_RELATED_DATA',
    'CREATE_RELATED_DATA_SUCCESS',
    'CREATE_RELATED_DATA_FAIL',

    'UPDATE_RELATED_DATA',
    'UPDATE_RELATED_DATA_SUCCESS',
    'UPDATE_RELATED_DATA_FAIL',

    'DELETE_RELATED_DATA',
    'DELETE_RELATED_DATA_SUCCESS',
    'DELETE_RELATED_DATA_FAIL'
];
